version: '3.4'

services:
  cats-api:
    image: ${DOCKER_REGISTRY-}catsapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
    - db
  
  db:
     image: "mcr.microsoft.com/mssql/server"
     environment:
        SA_PASSWORD: "c@ts@061015"
        ACCEPT_EULA: "Y"
  